version: '3.9'

services:
  dzoms-user-settings-service-postgres:
    image: postgres:16.1
    container_name: dzoms_user_settings_service_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: user_settings_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    networks:
      - dzoms_user_settings_service_net

networks:
  dzoms_user_settings_service_net: